image: openjdk:alpine

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew


stages:
  - build

build:
  stage: build
  script:
    - echo $(pwd)
    - ./gradlew build
